# Generated by Django 5.1.3 on 2024-12-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_adduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adduser',
        ),
    ]
